[package]
name = "wrike_driver"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
url = "2.2"
async-std = "1.10" # Optional, for async runtime support

